## Scott Bing - BSSD 5350 - Lesson 2 - Working with Matricies

In [1]:
import numpy as np

In [2]:
# Question 4 

# Define the matricies
A = [[3, -1, 2],
     [-2, 4, 0]]
B = [[2,  0],
     [-1, 4],
     [-3, 2]]

In [3]:
# convert matricies to arrays
matrixA = np.array(A)
matrixB = np.array(B)

# use numpy's dot product function
matrixA.dot(matrixB) 

array([[ 1,  0],
       [-8, 16]])

In [4]:
# Question 7
# Commutative property of multiplication 

# use numpy's dot product function
matrixB.dot(matrixA) 

array([[  6,  -2,   4],
       [-11,  17,  -2],
       [-13,  11,  -6]])

In [5]:
# Question 12 

# Define the matricies
A =  [[ 3, -2, 5],
     [ 0, -1, 6],
     [-4, 2, -1]]
B = [[ 2, -1, 0],
     [ 3, -5, 2],
     [ 1,  4, -2]]

In [6]:
# convert matricies to arrays
matrixA = np.array(A)
matrixB = np.array(B)

# use numpy's dot product function
matrixB.dot(matrixA) 

array([[  6,  -3,   4],
       [  1,   3, -17],
       [ 11, -10,  31]])